name: wlts-compendium-python
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - attrs=21.2.0
  - boost-cpp=1.70.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2021.5.30
  - cairo=1.16.0
  - certifi=2021.5.30
  - cfitsio=3.470
  - click=7.1.2
  - click-plugins=1.1.1
  - cligj=0.7.2
  - curl=7.71.1
  - cycler=0.10.0
  - dbus=1.13.18
  - decorator=4.4.2
  - expat=2.4.1
  - fiona=1.8.13.post1
  - fontconfig=2.13.1
  - fonttools=4.25.0
  - freetype=2.10.4
  - freexl=1.0.6
  - gdal=3.0.2
  - geopandas=0.9.0
  - geopandas-base=0.9.0
  - geos=3.8.0
  - geotiff=1.6.0
  - giflib=5.2.1
  - glib=2.69.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - hdf4=4.2.13
  - hdf5=1.10.6
  - icu=58.2
  - joblib=1.0.1
  - jpeg=9d
  - json-c=0.13.1
  - kealib=1.4.14
  - kiwisolver=1.3.1
  - krb5=1.19.2
  - ld_impl_linux-64=2.35.1
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=7.71.1
  - libdap4=3.19.1
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgdal=3.0.2
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=9.3.0
  - libkml=1.3.0
  - liblapack=3.9.0
  - libnetcdf=4.6.1
  - libopenblas=0.3.17
  - libpng=1.6.37
  - libpq=12.2
  - libspatialindex=1.9.3
  - libspatialite=4.3.0a
  - libssh2=1.9.0
  - libstdcxx-ng=9.3.0
  - libtiff=4.1.0
  - libuuid=1.0.3
  - libxcb=1.14
  - libxml2=2.9.12
  - lz4-c=1.9.3
  - mapclassify=2.4.3
  - matplotlib=3.4.2
  - matplotlib-base=3.4.2
  - munch=2.5.0
  - munkres=1.1.4
  - ncurses=6.2
  - networkx=2.6.3
  - numpy=1.20.3
  - olefile=0.46
  - openjpeg=2.3.1
  - openssl=1.1.1l
  - pandas=1.2.5
  - pcre=8.45
  - pillow=7.2.0
  - pip=21.0.1
  - pixman=0.40.0
  - poppler=0.90.1
  - poppler-data=0.4.11
  - postgresql=12.2
  - proj=6.2.1
  - pyparsing=2.4.7
  - pyproj=2.6.1.post1
  - pyqt=5.9.2
  - python=3.8.11
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pytz=2021.1
  - qt=5.9.7
  - readline=8.1
  - rtree=0.9.7
  - scikit-learn=0.24.2
  - scipy=1.6.3
  - setuptools=58.0.4
  - shapely=1.7.1
  - sip=4.19.13
  - six=1.16.0
  - sqlite=3.36.0
  - threadpoolctl=3.0.0
  - tiledb=2.2.9
  - tk=8.6.11
  - tornado=6.1
  - wheel=0.37.0
  - xerces-c=3.2.3
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - charset-normalizer==2.0.6
    - descartes==1.1.0
    - idna==3.2
    - jinja2==3.0.1
    - jsonschema==4.0.1
    - git+https://github.com/brazil-data-cube/lccs.py@v0.8.0
    - git+https://github.com/brazil-data-cube/wlts.py@v0.8.0
    - lxml==4.6.3
    - markupsafe==2.0.1
    - pyrsistent==0.18.0
    - python-sld==1.0.10
    - requests==2.26.0
    - urllib3==1.26.7
